### ISSUE TITLE
DWR streams & lakes reference layers

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#11]
As a user, on the map tab, I'd like to be able to turn on/off DWR streams and lakes as a map reference layer. 

Default to on and label the id.

**Comment by stdavis** [comment]
Waiting for data...

**Comment by stdavis** [comment]
From Eric:
>On the labeling, "Water_Name" would be best to use for labeling if its not too crowded.  And if we can symbolize the lines with bright dark blue at 1.5, that would be great.  And I think we can stage the data in an SDE location that you can pull from occasionally for updates.  Once this dataset gets fully populated, there shouldn't be changes more than once a year.  So if we can create a script to run as needed to do the update that would work best.

**Comment by jpechmann** [comment]
Put toggle under Settings.

**Comment by stdavis** [comment]
Also, switch the search box to point to the new streams and lakes data.
