### ISSUE TITLE
CRITICAL:  Cannot Submit Report

### ISSUE THREAD

**Issue by ericedgley** [agrc/electrofishing#110]
After creating a new station and adding all necessary survey info, I worked and added a "pass" of data and I get a generic error "cannot submit report".  There are no highlighted boxes as to where the error is or any other indication.  I have tried to change up data to get it to submit, but no success.   

**We are completely unable to test if there is no indication here as to the reason why.**
![error1](https://user-images.githubusercontent.com/38008975/38201563-fd72010a-3655-11e8-8f3b-fb39ed748f6a.jpg)

**Comment by steveoh** [comment]
> We are completely unable to test if there is no indication here as to the reason why.

There are plenty of layout and color enhancements that can be tested and verified without submitting reports. Please verify those tasks while we sort out the GP tool issue.

**Comment by steveoh** [comment]
The feature classes were not registered as versioned. The submission should work now that they are registered.
