### ISSUE TITLE
Move 'Survey Purpose' to Location tab

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#111]
Method tab > ‘Survey Purpose’ (Purpose of collection) > Add to the Location page, rather than nested within the Method tab, Equipment subtab.  

Rename field from 'Survey Purpose' to 'Survey Purpose (Purpose of Collection)'  AND move to the Location page.  Relocate field directly above the 'Weather' field.

Previously referenced as #20 in Google Word Doc & AGRC GitHub #59 

Now referenced as UDWR #401

**Comment by steveoh** [comment]
original #59 
pr #93
