### ISSUE TITLE
Increase upper threshold of values in the '# Netters' field

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#112]
Method  > Backpack, Canoe/Barge, Raft/Boat tabs > # Netters field > Only able to enter values between 1 - 3.   Please change to a Short integer with a max value of 20.

Referenced as UDWR #402

Method > Backpack, Canoe/Barge, Raft/Boat tabs > Duration/Pedal Time (seconds) field > Only able to enter values between 1 - 1000. Increase upper threshold to 7,200

Referenced as UDWR #403

**Comment by steveoh** [comment]
original #43
pr #106
