### ISSUE TITLE
Allow for one decimal point in 'pH' field

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#114]
Habitat tab > pH field > Allow for one decimal point. Have the values be to 1 decimal place with limit between 0 and 14. (e.g. 7.3 or 11.6) Currently only accepts whole numbers.

Previously referenced as #31 and #62 in Google Word Doc & AGRC GitHub #60

Referenced as UDWR #404

**Comment by steveoh** [comment]
original #60 
pr #107
