### ISSUE TITLE
Change data types in the Catch tab, Diet sub-tab

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#116]
- [ ] In the Diet sub tab, when a user selects 'Presence' in the Type field, the Measurement value should be a text field with a Yes or No option.  

- [ ] In the Diet sub tab, when a user selects 'Count' in the Type field, the Measurement field should be a small integer data type with no upper limit.  Currently a text field.

- [ ] In the Diet sub tab, when a user selects 'Volume (ml)' in the Type field, the Measurement field should be a small integer data type with no upper limit.  Currently a text field.

- [ ] In the Diet sub tab, when a user selects 'Weight (g)' in the Type field, the Measurement field should be a number that allows one decimal point and have an upper limit of 1500.  Currently a text field.

Previously referenced as #11a in the Google Word Doc

Referenced as UDWR #406

**Comment by stdavis** [comment]
Related Database Changes:
- [ ] Change field type of Diet:MEASUREMENT from Short to Double to be able to support the Weight type of measurement.

**Comment by stdavis** [comment]
I'm not sure that it's possible to switch out the editor for a dgrid column after it's been initialized. I'm going to label this as won't fix for now since there's nothing that will prevent data from being entered. We can look at this down the road.
