### ISSUE TITLE
Add Additional Required fields

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#118]
Make the following fields required:  Observers, Stream Reach, and Survey Purpose (Purpose of Collection)

Indicate required field as before with an asterisk (*) and warning prompt

Referenced as UDWR #408

**Comment by stdavis** [comment]
Stream reach is already required, right?
![image](https://user-images.githubusercontent.com/1326248/40547730-e9f027b0-5fef-11e8-992e-8cf01487ee30.png)
Maybe I'll replace the word "location" with "stream reach" in the error message...
