### ISSUE TITLE
Delete and Add multiple rows

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#124]
~Catch tab > Ability to select multiple rows and apply a function (i.e. select multiple rows to add ‘No Weights’ to a selected group versus current format of having to select individual individual fish to applying data to it).~ (duplicate of #49)

~Catch tab > Ability to specify and add multiple rows at once utilizing the “Add Row” function.  For instance, a user can only add one row at a time, which is time consuming and not feasible, when a user needs to add 108 records of SCMT that have no weight and length.  HANDLED BY ADDING COUNT FUNCTIONALITY.~ (duplicate of #49)

~Needs row delete function.~ (duplicate of #87)

Previously referenced as #22 in Google Word Doc.

This this issue being addressed by AGRC GitHub #87?   

Referenced as UDWR #414

**Comment by stdavis** [comment]
I believe that all of the items in this issue are already represented in other issues. I've updated the description to show this. Please let me know if I missed anything.
