### ISSUE TITLE
Addition and Deletion of Equipment types

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#126]
Method > line between electrofisher incidences needs to be there for all additions. Tabbing will highlight a “-” button and then enter will activate the “-” button function; deleting a record.  

Previously referenced as #64 in Google Word Doc.  

This issue is better discussed with the AGRC in person with a face-to-face meeting. Date TBD (Eric E. will be reaching out to coordinate a time and date).

Referenced as UDWR #416

**Comment by stdavis** [comment]
In other words, there's no way to delete the last piece of equipment. We need to add a minus button to the last item.

![image](https://user-images.githubusercontent.com/1326248/38835160-ea465788-4187-11e8-8a53-3b42e1723a49.png)

**Comment by nathankota** [comment]
Validated both equipment and tags w/Todd. Will confirm w/Craig.

**Comment by nathankota** [comment]
validated
