### ISSUE TITLE
Error message when submitting a report

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#155]
We are receiving a generic error message at time of submission and unable to submit an entry.  This error has happened with new stations and existing stations.  We've received it after filling out all fields as well as filling out the bare minimum.  I wish I had more to provide you with but it has been difficult to pinpoint the cause and has been very inconsistent.  We've tried old stations, new stations, with and without entering habitat information, clearing our browser history, etc..

![errorwoerrormessage](https://user-images.githubusercontent.com/35234370/40794924-c4af8338-64bd-11e8-8ea6-86da1adcfb79.PNG)

**Comment by stdavis** [comment]
Looks like some issue with the database or perhaps the way that I'm starting/stopping editing:
![image](https://user-images.githubusercontent.com/1326248/40795640-eeede03e-64bf-11e8-80e4-ef18c272a512.png)

**Comment by steveoh** [comment]
@stdavis did you say there was a screenshot of the method tab information? Can you paste that here?

**Comment by ericedgley** [comment]
![capture](https://user-images.githubusercontent.com/38008975/40806918-1bd54b6c-64e0-11e8-924c-1315348a664d.JPG)

**Comment by steveoh** [comment]
thanks @ericedgley! Can you send a screenshot of the methods tab as well? The more data we have the better.

**Comment by stdavis** [comment]
That is the method tab. :)

**Comment by steveoh** [comment]
Ha, I saw equipment and ... well ... i'm not very smart.
