### ISSUE TITLE
Diet.MEASUREMENT field data type

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#156]
I'm seeing this error message in server:
![image](https://user-images.githubusercontent.com/1326248/40796267-c77726e4-64c1-11e8-8e02-27f54cc549e5.png)

I'm guessing that this is because the user entered a string for the Measurement field in the Diet tab. Currently, the type for this field is set to `Double`. It's gone through several iterations:

Originally, we were told that this field type should be `Int` and "INTEGERS ONLY NO TEXT": https://github.com/agrc/electrofishing/issues/52

Then we were asked to make the field type conditional upon the value in the `Type` field: https://github.com/agrc/electrofishing/issues/116.

We can only pick one type for this field. What do you want it to be? Text would allow for any value but you would loose some numeric analysis capabilities.

**Comment by ericedgley** [comment]
After conferring with Craig on this, lets maintain the double float because most data entries will be numeric, but in the case for "presence", lets show this as a "0" or "1".  In the menu it would say "presence (0/1)".

**Comment by stdavis** [comment]
OK. We'll keep the field type as double. As for a drop down in the grid for this field: we can't dynamically switch between a numeric text box and a drop down within a grid. So you will need to choose just one. I'm guessing that it will need to be a numeric drop down. I'll make the switch to a numeric input in the app and close this issue. Feel free to comment if there's more to do on it and I'll reopen it.
