### ISSUE TITLE
Add Relationship Between Stations and Streams/Lakes Data

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#195]
Add a new step to the "Add New Station" dialog that asks the user to choose a specific stream/lake feature to associate with the station.

- [x] Add stream/lake data to the SDE database
- [x] Add new field to the Stations feature class to store the related stream/lake id.
- [x] Add new relationship classes to define relationships between stations and stream/lake feature classes.
- [x] Add new controls to the new station dialog to allow the user to select a feature.

**Comment by ToddVolkening** [comment]
![Capture of error during test 10 23 19](https://user-images.githubusercontent.com/35234370/67419104-4c3e8080-f589-11e9-9436-8a7e2390889b.PNG)

The station creation process appears to be working correctly.  However, the error shown in the image above is encountered once you add a station and attempt to "verify location" for the associated event reach.  This error prevents any further testing of GitHub issues #197, #56, #5, #39, #10, and #1.  

-CW, TV

**Comment by stdavis** [comment]
I'll get this fixed within the next hour...

**Comment by stdavis** [comment]
@ToddVolkening Give it another try. I believe that I have the issue fixed.

**Comment by ToddVolkening** [comment]
Looks good to us.  Thank you

TV and CW
