### ISSUE TITLE
Request Production SDE Database

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#205]
Name: Electrofishing
Users: WildView & WildAdmin (password can be randomly generated or I can provide them)

**Comment by MichaelAGRC** [comment]
This has been created.  I've requested electrofishing.agrc.utah.gov for a DNS entry.  User/pass pairs used from document Electrofishing Information.

**Comment by nathankota** [comment]
@MichaelAGRC we're okay to close this issue, yes?

**Comment by MichaelAGRC** [comment]
Yes.
