### ISSUE TITLE
Figure out application deployment pipeline.

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#209]
Will DWR/DTS allow us to push directly to the production servers in a similar manner as the test server?
Do our users that were set up for the test server have access to prod?

**Comment by nathankota** [comment]
Aaron is out sick this week, but Sam informed me that they must submit a change request and go through hosting to push to production.

**Comment by stdavis** [comment]
So, I'm assuming that this means that we send someone a .zip file and they deploy it?

**Comment by nathankota** [comment]
Not sure yet. Will follow-up when I have more info from Aaron.

**Comment by nathankota** [comment]
From Aaron:
"Deploys to production have to go through DTS Campus D Hosting group, specifically Atilio Medina.  

Step0:  Security 524 form complete.
Step1:  Fill out the change request.
Step2:  Provide the software to Atilio to copy to the server folder.  Typically we use a google shared drive.
Step3:  Test

Let me know if you want me to fill out the change and what date your looking to deploy.  Deploys on Fridays are frowned upon."

I will start working on getting a 524 form from DWR, and we will have Aaron do the change request. When should we shoot for that request?

**Comment by stdavis** [comment]
It doesn't matter to me. I just need a few days notice to make sure that I have all of our ducks in a row. It may actually take a few deploys to get everything working correctly. It seems like the first deploy to production never works on the first try.

**Comment by nathankota** [comment]
Send build files to DWR DTS (Aaron Heyman) and he does a change request for the deploy.
