### ISSUE TITLE
Upgrade ArcGIS Server version

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#227]
Currently, this app is running on 10.5. At some point DWR is going to want to upgrade their ArcGIS Server to the latest version. The app will need to tested and any bugs fixed.

This will require some coordination with DWR.

**Comment by stdavis** [comment]
Buck gave the green light on this today. There aren't any other services on that machine other than electrofishing.

**Comment by stdavis** [comment]
Steps for an upgrade:
- [ ] download ArcGIS Server 10.8.1 web adaptor and arcgis server installs
- [ ] uninstall old web adaptor
- [ ] run new web adaptor installer
- [ ] run arcgis server installer
- [ ] update system PATH to point to new 10.8 python folders
- [ ] `pip install pyodbc`

I've tested this successfully in development.

**Comment by nathankota** [comment]
@stdavis Craig said any Friday after 5 p.m. will be fine for the upgrade. Let me know when you'd like to schedule it (this Friday?) and I'll have him warn the users.

**Comment by stdavis** [comment]
Let him know that I'll do it this Saturday. Thanks!

**Comment by steveoh** [comment]
10.9 is right around the corner if you think that would be worth waiting for.

**Comment by stdavis** [comment]
I think that I'd rather go with 10.8 rather than gamble with a new minor release.

**Comment by stdavis** [comment]
Completed today. Everything seems happy.

**Comment by nathankota** [comment]
Obtain ECP file from DWR

**Comment by stdavis** [comment]
I was able to re-authorize using the newly provided license file this morning without any issues.
