### ISSUE TITLE
Disable Event Dates in the Future

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#250]
Don't allow the user to select an event date that is in the future.

**Comment by stdavis** [comment]
The fix for this issue has been pushed to [dev](https://electrofishing.dev.utah.gov/) as part of the [v2.3.0-0 pre-release](https://github.com/agrc/electrofishing/releases/tag/v2.3.0-0).

**Comment by nathankota** [comment]
I could finagle the Collection Time to be greater than the current time, but the Collection Date works well to not allow a day in the future.
