### ISSUE TITLE
Migrate services etc. from, and deprecate, GRAS113SP

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing#254]
Move data, geoprocessing, etc. services that are specific to the electrofishing application from the existing ArcGIS server onto a different DNR/DWR server (WRI?) to enable deprecation of gras113sp. Challenges/considerations are:

- version differences
- licensing mismatches
- ...

**Comment by nathankota** [comment]
Could [GRWWRISP/AT](https://docs.google.com/spreadsheets/d/1IlNJ49KxLwDV8x3VCC5aopq6Y5Iikie05ZGhWDb8ckQ/edit#gid=0) (the WRI servers) be a possible landing place? Looks like they are at 10.7 (electro at 10.8.1) and do not have advanced licensing.

**Comment by steveoh** [comment]
Was this completed with the data center exit?

**Comment by stdavis** [comment]
Yes! Thanks for the ping on this issue.
