### ISSUE TITLE
Firebase Token is not refreshing

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#262]
It appears that the firebase auth token is not refreshing after a certain period of time (1 hr?) and then all secured requests are returning a 403 with a plain text error message that causes issues with the app expecting JSON data.

![image](https://user-images.githubusercontent.com/1326248/182249978-2b31874b-b66c-45f0-b725-00b3c150e0c2.png)

**Comment by nathankota** [comment]
Craig was logged in for a couple hours, but accidentally closed the browser. He wanted to start fresh, so he cleared his cache and when trying to login for the first time received the following. On his second attempt he was able to login.

![Image](https://user-images.githubusercontent.com/15659642/226741855-2e6c9f7b-1a93-4f9c-932f-fa334aa4c5c5.png)



![Image](https://user-images.githubusercontent.com/15659642/226742966-bc69c6a3-752a-4402-907f-9a338c1f6b72.png)

**Comment by steveoh** [comment]
I wonder if that blue box is coming from utahid. I have yet to see that piece of UI and I don't think we wrote it.

**Comment by stdavis** [comment]
Ya, that looks like the sign-in popup which is all UtahID. We have no control over that service. It sounds like UtahID had an issue. I saw an email yesterday about some issue with it.

**Comment by nathankota** [comment]
Thanks for the feedback fellas. After more testing Craig and I accepted that it likely wasn't a firebase token issue and, in fact, after refreshing his browser and logging in after a submission event hung and did not complete, all the previously-entered data was still within the form and he was able to submit which, we think, confirms that the firebase token is working as expected? Validating this, and Craig will test again tomorrow, and will reopen if necessary.
