### ISSUE TITLE
Cloud App Testing Results

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing#263]
From Craig (9/21/2022):

> ### Location tab
> 
> 1) The stream name search tool on the add station window was not functional (i.e., the search tool was not populated with the stream names from the lookup table);
> 
> 2) An incomplete stream layer still occasionally appears on the add station window map even after clearing my cache and reloading the page;
> 
> 3) Selecting add station received a "token error" during 1 of my 3 attempts (see attached); and
> 
> 4) The token error mentioned in 3 above remained present when attempting to enter new information even after cancelling the error-related entry using the cancel buttons on both the add station popup and the main page.

> ### Method tab
> 
> ~1) Domain for backpack model is incorrect and shows canoe/barge and raft/boat model domains instead; and~
> 
> ~2) Fields in canoe/barge and raft/boat equipment type tabs are populated with information previously entered in fields in the backpack tab when you toggle between these equipment tabs.  The information from one tab should not carry forward to another tab.  Equipment type fields should only populate when the user has entered the information into them.~
> 
> ### Catch tab
> 
> All good.
> 
> ### General submission
> 
> 1) A token error was encountered when submitting entries (see attached).  No events were successfully created due to this error.

![image](https://user-images.githubusercontent.com/1326248/195117820-86c58914-8b54-418a-9388-7a9f80e82143.png)

![image](https://user-images.githubusercontent.com/1326248/195117883-2513b075-0a0f-4e32-9564-ecbf493c0634.png)

**Comment by stdavis** [comment]
> Domain for backpack model is incorrect and shows canoe/barge and raft/boat model domains instead;

This is not related to the migration to firebase hosting. It appears exactly the same in the current production app. I've opened a [new issue](https://github.com/agrc/electrofishing/issues/268) for it.

**Comment by stdavis** [comment]
>Fields in canoe/barge and raft/boat equipment type tabs are populated with information previously entered in fields in the backpack tab when you toggle between these equipment tabs. The information from one tab should not carry forward to another tab. Equipment type fields should only populate when the user has entered the information into them.

This is also not related to the migration to firebase hosting. It appears exactly the same in the current production app. I've opened a [new issue](https://github.com/agrc/electrofishing/issues/269) for it.

**Comment by stdavis** [comment]
I believe the remaining items that this issue references are directly related to #262.

**Comment by stdavis** [comment]
This is old. Any new issues are being tracked separately.
