### ISSUE TITLE
Habitat tab - adjust data field positions

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing#265]
> % pool,% riffle, and % run should be listed in sequence.  Please move "presence of spring" field in front of or behind (e.g., above or below) the % pool, % riffle, and % run fields

**Comment by stdavis** [comment]
Before:



![Image](https://user-images.githubusercontent.com/1326248/224140820-2d87465a-f890-4997-8a72-b7c5c4bc7022.png)



After:


![Image](https://user-images.githubusercontent.com/1326248/224140748-1418d2a1-ca7a-4011-85b7-a6185a70c3f6.png)

**Comment by nathankota** [comment]
Validated w/Todd. Will confirm w/Craig.

**Comment by nathankota** [comment]
validated
