### ISSUE TITLE
Craig's latest error

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#283]
![Image](https://user-images.githubusercontent.com/1326248/221623396-3b557b49-7b12-404f-a8e8-16a979df92e7.png)

**Comment by stdavis** [comment]
I'm not sure what's going on. The error message seems to indicate a database issue. I couldn't find anything in the ArcGIS Server logs. I have compressed the database since he ran this test. That's all that I've got as far as ideas for now. I've been able to submit dozens of reports without issue. If he runs into this again, I'd like to know exactly what data he is attempting to submit (values for every field that he has filled out in the report).

**Comment by steveoh** [comment]
Do you want to add some sort of logging call that can send this data to google using firebase analytics or otherwise?

**Comment by steveoh** [comment]
I wonder now if the toolbox tried to insert a value that was formatted funny based on the syntax error suggestion?
