### ISSUE TITLE
update or new Archer?

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing#293]
- with new [lucid diagrams](https://lucid.app/lucidchart/1c1c9390-7cc8-41e2-b3ae-257d3d8a7602/edit?invitationId=inv_04358ba0-0c02-42e5-b4fd-32a99639b875&page=0_0#)
- agency contacts?
- machine names (Documentation > Readiness Checklist) should be the wri machine once we're fully migrated to the firebase-hosted app

**Comment by nathankota** [comment]
/remind me about this in three weeks

**Comment by stdavis** [comment]
/remind @nathankota about this in three weeks

**Comment by steveoh** [comment]
Bramwell updated the current one for the api.

**Comment by nathankota** [comment]
/remind me in one week to schedule some time with Ryan to update this

**Comment by stdavis** [comment]
@nathankota Do you know if this was ever resolved? I feel like this project is up-to-date with Archer.

**Comment by nathankota** [comment]
> @nathankota Do you know if this was ever resolved? I feel like this project is up-to-date with Archer.

Annual Risk Assessment completed with Trevor Keller June 10, 2024. He confirmed via chat today that we are good to go until next year's annual assessment, even though neither of us can find the assessment in the Archer app. I also sent the latest network and data flow diagrams, and he confirmed that they are updated.

![image](https://github.com/user-attachments/assets/ef4e5d10-86b8-40ad-a70d-9a4c007e725d)
