### ISSUE TITLE
Allow decimals on Transect measurements

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing#298]
The new app should operate similarly to the existing production app and allow decimal values for Habitat >Transects > depth, velocity, distance. 

Current app: (correct - allows decimals)
![image](https://user-images.githubusercontent.com/15659642/226976524-72dd3c83-7709-49f0-9fa3-16c31dd905c0.png)

New app: (incorrect - allow decimals, and no error message required)
![image](https://user-images.githubusercontent.com/15659642/226976724-859b159b-2948-44ab-9b75-339d66d198b6.png)

**Comment by nathankota** [comment]
No indication yet from client about a limit on the decimal places

**Comment by stdavis** [comment]
I'm not sure if we have the ability to limit decimal places anyways...

**Comment by nathankota** [comment]
> I'm not sure if we have the ability to limit decimal places anyways...

Ah, okay. If it is possible, then only allow out to the hundredths place.

**Comment by steveoh** [comment]
input type number can take a step value that kind of limits the decimal places. Then validation libraries can also handle that logic as well.

**Comment by stdavis** [comment]
I guess that I wasn't clear. I'm not sure if we have the ability to limit the number of decimal places _without some significant additional work_.

**Comment by nathankota** [comment]
> ...I'm not sure if we have the ability to limit the number of decimal places _without some significant additional work_.

Minimizing work and time on this is the key, and an enhancement can be done later, if necessary and desired.

**Comment by stdavis** [comment]
The fix for this issue has been pushed to [dev](https://electrofishing.dev.utah.gov/) as part of the [v2.3.0-0 pre-release](https://github.com/agrc/electrofishing/releases/tag/v2.3.0-0).
