### ISSUE TITLE
Habitat Tab: allow decimals on some fields

### ISSUE THREAD

**Issue by nathankota** [agrc/electrofishing#313]
Allow up to one decimal place to be entered in the following fields:

- pH
- Conductivity
- Dissolved Oxygen
- Total Dissolved Solids
- Turbidity
- Alkalinity

**Comment by stdavis** [comment]
@nathankota This is ready for acceptance testing in: https://electrofishing.dev.utah.gov/

**Comment by nathankota** [comment]
Looks like the fields allow quite a few significant digits to be entered manually, but that seems to match how fields on other pages work (e.g. Method). I will confirm with client.

**Comment by stdavis** [comment]
Yes, we don't have a way to limit the number of significant digits in this app at the moment. It's either whole numbers or decimals.

**Comment by nathankota** [comment]
> Yes, we don't have a way to limit the number of significant digits in this app at the moment. It's either whole numbers or decimals.

Ah, thanks for the clarification. This task is validated.
