### ISSUE TITLE
"No stream segments selected..." reach warning should be non-blocking

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#35]
This needs to be changed to a non-blocking warning:
![image](https://cloud.githubusercontent.com/assets/1326248/21697682/c59e7d12-d350-11e6-8c57-97c27103f60a.png)

In other words, don't require the points to snap to a stream segment. There may be cases in which there are no existing stream segments. If there are no stream segments then draw a straight line between the start and end points.

**Comment by keatonwalker** [comment]
This issues is slightly related to the stream segment [punting comment](https://github.com/agrc/electrofishing/blob/master/scripts/Scripts/GetSegmentFromCoords.py#L95). Right now the verification of a stream segment can only span 2 reach codes at most. That is, if the start and end point snap to stream features with different reach codes, all other segments in between must have either code.

@stdavis do you know if we will need to make it span more than 2 reach codes in the future?

**Comment by stdavis** [comment]
I don't know. But we should make it work no matter how many reach codes it spans even if we draw a straight line.
