### ISSUE TITLE
Segments generated by start/distance/direction are periodically truncated

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#40]
I wonder if this is due to a stream that's broken up into multiple features...

![image](https://cloud.githubusercontent.com/assets/1326248/21698413/18259c84-d354-11e6-882d-107d53207f81.png)
![image](https://cloud.githubusercontent.com/assets/1326248/21698421/1cedf07c-d354-11e6-8930-a897a7327aec.png)
![image](https://cloud.githubusercontent.com/assets/1326248/21698426/20be882e-d354-11e6-91f3-d73c9ef94f10.png)

**Comment by keatonwalker** [comment]
I think this is cause by distances that span more than one reach code. The fix may also be helpful for #35.
