### ISSUE TITLE
Enable the counting of many fish without lengths or weights

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#49]
Often, the field workers will no weigh and measure every fish. Once they feel like they have a good sample size, they will simply count the rest without measurements (they still record species). Currently, they would still have to add an empty row for each fish that they count. They would like a way to enter a single row for many fish to streamline data entry. This could be done with an extra "Count" field in the catch table. Or some other way to signify that a row is to be recorded as more than one fish.

We need to decide how to represent this in the app as well as decide how to model in the database. Do we want to keep the duplicate rows in the database or use some sort of count field? I'm leaning toward keeping the duplicate rows in the database. This seems to be the most straightforward to me.

Ref 9) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit which we further clarified in a meeting.

**Comment by stdavis** [comment]
@ToddVolkening Would something like this work for this issue?
![image](http://g.recordit.co/xMwuroyyEI.gif)

I do think that adding a count field to the fish table in the database adds unnecessary complexity and would be a bad idea. So the app would just add duplicate records to the table for any counts that are more than one.

Let me know what you think.

**Comment by stdavis** [comment]
Actually, I was just thinking that this could replace the batch button (which was never a great solution in my opinion because of the requirement to add a bunch of empty rows). We could say if there's a value entered for weight and the count column is more than one, then the weight is averaged.

**Comment by ericedgley** [comment]
After conferring, the one big problem with this solution is that by removing the "batch" weight button and just using the "count" disables the ability to have variable lengths for a "batch" group of fish.  This needs to be maintained.  But it does fix the problem with needing to add higher counts of fish with no length or weight.  

So, keep the batch function as is and add the "count" column right after species that you would need to tab through.
