### ISSUE TITLE
Show additional data in station map popup

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#56]
They want to see additional fields in the popup:
>Show callout with Water Name, Water Id, Location information for pinned stations on map when clicked on.  Call out to include Station Name, Water Name, Water Id, Reach Code? Rather than its current format that only displays Station Name and Stream Type.  Or some way to identify where a created or temporary pin is relative to water identifiers.

Not sure if these are even in the data currently. Maybe have to search for nearest stream reach to station.

Also, not sure what they mean by this:
>Also, when you get a Successful Verification notice after submitting a survey location have the notice also include the Water Name, Water ID, Reach Code included in the notice.

There is no successful verification notice after submitting a new station location.

Ref 16) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by stdavis** [comment]
I think that this is the only relevant portion left for this issue:
>Show callout with Water Name, Water Id, Location information for pinned stations on map when clicked on. Call out to include Station Name, Water Name, Water Id, Reach Code? Rather than its current format that only displays Station Name and Stream Type. Or some way to identify where a created or temporary pin is relative to water identifiers.

**Comment by stdavis** [comment]
I think that the only additional attribute that we can do without database changes or some other significant amount of work is water id.

**Comment by ToddVolkening** [comment]
What has been provided as "water id" is not a coding that would be recognized by the end user.  We would prefer the pop-up to show either data present in the DWR_WaterID or ReachCode, not data from the Permanent_Identifier field.  Thanks.

~TV and CW

**Comment by stdavis** [comment]
`Permanent_Identifier` is the only field in the stations feature class that is related to the streams/lakes data and consequently, the only waterbody-related field that we can show in the popup without some significant work. Would you like me to remove the popup for the moment? 

Where does this fit into the priority list relative to the rest of the issues?

**Comment by stdavis** [comment]
I just pushed v1.9.1 that removed the permanent id from the station popup.

**Comment by stdavis** [comment]
I also added a new issue to track adding the related data for a future release: https://github.com/agrc/electrofishing/issues/204
