### ISSUE TITLE
Add "Survey Purpose" to Method Tab

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#59]
Drop down values: Depletion estimate, Mark-Recapture, Disease certification, Presence/absence, Fish community, Fish propagation, Catch and Effort, Non-native fish removal, Genetics, and Other

Ref 20) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by steveoh** [comment]
this should have closed with #93
