### ISSUE TITLE
Add minus button to newly created equipment widgets

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#63]
>Add a minus button (-) to each additional type of equipment added (e.g. when a second backpack shocker is added include a minus (-) sign, to accompany the plus (+) signs that's present, so that a user is able to delete the record if needed.  Add a minus (-) button for each record added.  Each piece of equipment should have a plus (+) and minus (-) button associated with it.

Ref 36) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

I don't think that we want a minus button if there is only one left. But otherwise, there should be one. I believe that this will affect tags (fish dialog) as well.

**Comment by ToddVolkening** [comment]
The last piece of equipment added should have both a plus and minus button.

**Comment by stdavis** [comment]
Superseded by #126
