### ISSUE TITLE
Species Code & Length Type drop downs are not being cleared on submission

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#65]
>After submitting a report, it appears that the data from a previous submission carried over and prepopulated the first entry with  “Species Code” and “Length Type” fields from the previous submission.

Ref 38) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by steveoh** [comment]
I cannot replicate this with the current code base. @stdavis will you verify that this is still an issue and close it if you also cannot reproduce.

**Comment by stdavis** [comment]
I couldn't reproduce this on `master`.
