### ISSUE TITLE
Pre-populate values for equipment

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#66]
When adding new equipment...
>If using the same unit and settings for 2 units, auto populate new unit with previous units info when new unit is added.

Ref 50) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by steveoh** [comment]
I don't understand what units are being referenced here. All of the fields have the unit in parenthesis where applicable so I'm not sure what can be pre-populated.

@stdavis do you have a better understanding of what this is asking for or if it is valid?

**Comment by stdavis** [comment]
I'm guessing that by _units_ they mean _values_. In a similar way that the catch grid prepopulates the Species and Length type when creating new rows.
