### ISSUE TITLE
Radio Button Group Contrast

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#68]
> Greater color differential for passes when active vs. inactive.

Ref 52) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

Increase the contrast between bootstrap radio buttons in a group.

**Comment by steveoh** [comment]
Original 

![image](https://user-images.githubusercontent.com/325813/36753195-b626e84a-1bc2-11e8-8b81-a3a16b87bda6.png)
