### ISSUE TITLE
Select Text In Previously Populated Field on Navigation

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#70]
>When moving to already populated field, e.g., weight, can the value be highlighted so that onset of typing results in replacement rather than cursor at the end of entered value and a need for user to manually delete characters?

Ref 56) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by stdavis** [comment]
This is fixed with the new DataGrid component.

**Comment by nathankota** [comment]
Validated w/Todd, confirm w/Craig.
When using tab it works as expected. On mouse click the cursor ends up at the end of the entered data. Seems fine?

**Comment by nathankota** [comment]
validated
