### ISSUE TITLE
Reformat Species Count Summary

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#77]
>When submitting a report, show counts by pass with rows being for fish species and columns being for pass # to allow for easier comparison of counts for passes 1, 2, 3, … 

Currently, the summary looks like this:
![image](https://user-images.githubusercontent.com/1326248/34727950-b3385638-f515-11e7-8be9-c698195dd4a1.png)

We need to combine the separate pass tables into a single table with the species as rows and each column a separate pass.

Related to #69.

Ref 74) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by nathankota** [comment]
validated
