### ISSUE TITLE
Query/Report Application

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#86]
From [SOW](https://docs.google.com/document/d/1E7wbIk-QmsNL-QhASyw_nuLCMZnk9iQShwKLJg7hbpA/edit#):
![image](https://user-images.githubusercontent.com/1326248/34730090-ae50e166-f51b-11e7-8b37-936a109c3f6b.png)

> A report created (e.g. length histogram) would be specified as metric
or imperial (standard) units prior to report creation.

Ref 63) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by stdavis** [comment]
More info from Craig: [Query fields (1).docx](https://github.com/agrc/electrofishing/files/1656209/Query.fields.1.docx)

**Comment by stdavis** [comment]
This is really two separate requirements.
Data browser (a'la water chemistry):
- They want to be able to select collections events from multiple stations that may or may not be near each other to run reports on.
- Filter based on these fields: [Query fields (1).docx](https://github.com/agrc/electrofishing/files/1656209/Query.fields.1.docx)
- Interactively select stations/reports to then download, link to edit application or generate reports (see below).

Reports:
Craig will get us samples of each report (there are four) along with the math required to generate them.

Metric only for now with the idea that they could have an imperial (standard) option.

They want to be able to copy the charts into a google doc/word document.

**Comment by stdavis** [comment]
Report examples from Craig:
[Report fish per kilometer line chart.pptx](https://github.com/agrc/electrofishing/files/1917579/Report.fish.per.kilometer.line.chart.pptx)
[General event output for selected events.xlsx](https://github.com/agrc/electrofishing/files/1917580/General.event.output.for.selected.events.xlsx)
[Report length frequency histogram.pptx](https://github.com/agrc/electrofishing/files/1917581/Report.length.frequency.histogram.pptx)
[Report kg per hectare line chart.pptx](https://github.com/agrc/electrofishing/files/1917582/Report.kg.per.hectare.line.chart.pptx)

**Comment by steveoh** [comment]
Did the #'s change in the google doc?

> 63). Have english units for report options. Do They want to be able to toggle between english/standard and metric?

**Comment by stdavis** [comment]
No, I don't think so. I referenced 63 in the description just to capture the units stuff. I'm not sure that there was a line item in that google doc for the this new app.

**Comment by stdavis** [comment]
More report details from Craig:
[Calculations for charts.3.docx](https://github.com/agrc/electrofishing/files/2080724/Calculations.for.charts.3.docx)
[General event output for selected events.3.xlsx](https://github.com/agrc/electrofishing/files/2080725/General.event.output.for.selected.events.3.xlsx)
[Report fish per kilometer line chart.pptx](https://github.com/agrc/electrofishing/files/2080726/Report.fish.per.kilometer.line.chart.pptx)
[Report kg per hectare line chart.pptx](https://github.com/agrc/electrofishing/files/2080727/Report.kg.per.hectare.line.chart.pptx)
[Report length frequency histogram.pptx](https://github.com/agrc/electrofishing/files/2080728/Report.length.frequency.histogram.pptx)

**Comment by stdavis** [comment]
I think that this is part of agrc/electrofishing-query now.
