### ISSUE TITLE
Eliminate duplicate service requests to get domain data

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#96]
[This method](https://github.com/agrc/electrofishing/blob/1da8bf204022423f4a11e5c9d8c4e5930054eb39/src/app/Domains.js#L23) ends up making tons of duplicate requests to the same service. For example:
![image](https://user-images.githubusercontent.com/1326248/36907663-6e5a9d64-1df6-11e8-904e-068105aeb83f.png)

**Comment by steveoh** [comment]
Yeah all the information you need is in the first request.
